name: Yad2 Scraper

on:
  schedule:
    # Run every 15 minutes (between 06:00-20:00 UTC, i.e. 08:00-22:00 IL)
    - cron: '*/15 6-20 * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn install

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Run scraper
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          INGEST_URL: ${{ secrets.INGEST_URL }}
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: yarn scrape

      - name: Push new json data if needed
        run: |
          if [ -f ./push_me ]; then
            echo Pushing to Github...
            git add .
            DATE=$(date +"%F, %H:%M:%S")
            git commit -m "updated data - $DATE"
            git push
          fi
